### ISSUE TITLE
F# Intellisense

### ISSUE THREAD

**Issue by arcturius** [gmpl/FSharpPlus#11]
Hi, 

I have downloaded and trying to use latest FSharpPlus (VS2013 Premium Update 4, F# 3.1), but Intellisense seems to go crazy with the scripts like "Learn You a Haskell.fsx".. 

I copied the text from this script into .fs file. Intellisense initially processes the file for 10-15 mins consuming CPU and memory, but then crashed with error "Assembly reference FsControl.Core.dll was not found or invalid". The file FsControl.Core.dll exists in the folder and is valid. 

Sounds like a glitch in the VS / F# software. 

Did you experience this? If yes, any workarounds?

Thanks,
Pavel.

**Comment by gmpl** [comment]
Hi Pavel,

F# compiler is a bit slow doing overload resolution and in order to emulate Haskell typeclasses overload is used everywhere. Cases like this is where you start noticing long compile times and intellisense going crazy.
Still you can use <code>F#+</code> generic functions and get reasonable good compile times, things get worst as you define your own generic functions.
In short, using generic functions doesn't slow down the compiler but defining them yes.
My advice is, if you want to try <code>F#+</code> start with another script. If you want to play with the Learn You A Haskell samples, try running them one by one, not the entire script in one shot.

Regarding the Assembly reference not found error I haven't experience that, are you sure is it properly referenced in the Project?

**Comment by arcturius** [comment]
Yes, sounds like this is the issue. the error I am getting seems to me to be related to my PC. but over performance is not. did you try to contact Don Syme with F# compiler guys on this? I think it can be optimized/fixed.

**Comment by gmpl** [comment]
I will try to contact them to let them know. Indeed I prepared a [script](https://gist.github.com/gmpl/5c2fae2d6e6a115d729e) which shows how overload resolution slows down, specially with nested generics.
Anyway I don't think they will fix it. Hopefully I'm wrong but I think they have other priorities.

**Comment by cmeeren** [comment]
> In short, using generic functions doesn't slow down the compiler but defining them yes.

I know I am resurrecting a very old issue, but I'd just like to add my two cents. In my experience, extensively using generic functions like `map` seems to impact Intellisense performance quite a bit.
