### ISSUE TITLE
"error FS0192: internal error: GenUnionRef m" (solves by using FsControl 1.0.9)

### ISSUE THREAD

**Issue by ArtemyB** [gmpl/FSharpPlus#22]
Test code: `Some 1 >>= (fun x -> if x > 0 then Some x else None)`

Without explicitly downloading FsControl 1.0.9 FSharpPlus takes 1.0.13 at this moment. However there is no such error while using FsControl 1.0.9 (haven't tried versions between 1.0.9 and 1.0.13).

Seems like it is related to https://github.com/gmpl/FsControl/issues/38

**Comment by gmpl** [comment]
Thanks @ArtemyB indeed it is the same issue you are linking.
Now all versions higher than 1.0.9 are hidden.
This is my fault for not being faithful to the semantic versioning principles.

Hopefully version 2 of FsControl will be released soon and free of these problems. I'm waiting for the final release of F# 4.1 since it will be depending on the new features included there.
Specially the fixes for the insane compile times, but there will be other stuff.

In the meantime consider version 1.0.9 as the latest stable release.
You can still use the hidden and pre-release versions at your own risk.
