### ISSUE TITLE
What is the best way to migrate to F#+

### ISSUE THREAD

**Issue by robkuz** [gmpl/FSharpPlus#30]
Hi,

can/should one already move to this project from FsControl? And if so, what is the best way to do so?

**Comment by gmpl** [comment]
Hi @robkuz 
We're in the process of releasing the first stable version, but we will depend on the new F# 4.1 which at the moment is in RC2.

Having said that if you already use FsControl 2.x which was also a pre-release, you can replace it with FSharpPlus right now. In theory it should keep working since the namespaces are the same, no changes at the moment, except the generic operators module, which is now the one from FSharpPlus: <code>FSharpPlus.Operators</code> instead of <code>FsControl.Operators</code>.

So my advise is try using FSharpPlus, pre-release (tomorrow will try to upload a new nuget) but also keep an eye on the project since interesting changes are coming soon.

Another reason to move is to give us your valuable feedback ;) and please let me know if you have further questions.

**Comment by gmpl** [comment]
@robkuz The new FSharpPlus nuget is available at https://www.nuget.org/packages/FSharpPlus/1.0.0-CI00063 
Now you can try updating your project.

**Comment by robkuz** [comment]
OK. that worked OKish. The biggest issues I had was that I have my own `Choice` and my own `NonEmptyList` types that bombed the compile. The migration on a modestly sized project (5K LOC <) took me less that 90min.

**Comment by gmpl** [comment]
Thanks for your feedback.
Perhaps now that you're linking this whole library you can use ``NonEmptyList`` from here and save some LOCs.
For ''Choice`` you might want to wait until F# 4.1 is released and use the new ``Error`` DU which will be integrated here. Then you will save more LOC and improve a bit the performance.

**Comment by chinwobble** [comment]
any chance that the v1 of FSharpPlus will be compatible with FSharp 4.0?

**Comment by gmpl** [comment]
@chinwobble That was not in my priority list, since I don't see a good reason not to switch to F# 4.1 with all the new features, specially the new super-fast static constraints compiler which will allow you to exploit all features of this projects without any issues.

Having said that, this is an open source project and I'm just the maintainer, so I'm not the one who will take all decisions and if you will be using and thus testing it in F# 4.0 there are many chances we can keep it working on that platform, using conditional compilation which is already being used for .NET 3.5.

What doesn't make sense for me is to do all additional efforts to keep it working in F# 4.0 just for the sake of making it work 'just-in-case' someone will be using it. But as long as there is at least one real user, who is following the project, testing it, submitting issues, ideas, feedback and possibly PRs, justifies the additional effort and you'll still get support for F# 4.0.

So, at the moment I don't see any technical issues, indeed at the moment is working on F# 4.0.

Actually there are some projects around (including one that I did) that will not be immediately migrated to F# 4.1, but since we didn't reach V 1.0 still might be some small breaking changes that will need to be adjusted in the client code to use V1.

Can you possibly comment about your scenario? Are you evaluating using it in an open source project, commercial, prototype, scripting?

**Comment by chinwobble** [comment]
hi @gmpl, thanks for the quick and thorough reply. Regarding my current scenario, I am developing some moderately simple backend integration software hopefully using F#. I was hoping to leverage libraries like this one as an easy way to implement functional design patterns easily (though I am still learning). My company is rather conservative about upgrading software so it may be awhile till I get F# 4.1 at work. So I was hoping to continue to use this library for my F# 4.0 project if possible. 
Hope this answers your questions.

**Comment by gmpl** [comment]
Thanks @chinwobble then let's keep it compatible to F# 4.0, please report any issues with this.

**Comment by robkuz** [comment]
I'd like to close this one

**Comment by gmpl** [comment]
@robkuz Agreed, anyway it will be interesting to write something in the docs about this question.
In the meantime I will add a link to this discussion.
Thanks for your feedback, much appreciated.
