### ISSUE TITLE
NonEmptyList map gives me :: Seq<'b>

### ISSUE THREAD

**Issue by robkuz** [gmpl/FSharpPlus#37]
given a `NonEmptyList<'a>` and running that thru `FSharpPlus.Operators.map` I am getting a `Seq<'b>` where as I expected it to return a `NonEmptyList<'b>`. What am I doing wrong?
Only when I fully qualify the call to map like

    NonEmptyList.map transform someNonEmptyList

the result is the correct type of functor

**Comment by mausch** [comment]
Probably because I don't see any Map instances for NonEmptyList in https://github.com/gmpl/FSharpPlus/blob/master/src/FSharpPlus/Functor.fs#L213 .
Can you add one and see if that works?

**Comment by robkuz** [comment]
Sorry, I dont understand. What should I do exactly?

**Comment by gmpl** [comment]
@mausch the instance is [within the class](https://github.com/gmpl/FSharpPlus/blob/b2de448cc2daabace03b64d84ae5ee0331bc6134/src/FSharpPlus/NonEmptyList.fs#L37)
Although now the FsControl was merged we can put it in the Invokable, I have the impression that is good to keep the separation and only specify instances for primitive types in the Invokables.

@robkuz I think this issue was [recently solved here](https://github.com/gmpl/FSharpPlus/commit/c8dd546d80356eb582cfe10d25cea13f0aab3058) but probably you are using the latest nuget which is previous to that fix.

The problem is that in some cases interfaces "eats" all instances before the instance declared in the type. This happens because F# does some automatically conversions (upcasts) in some situations.

So I did some workarounds to give either less priority to the interfaces overload, incases when it's still usable, or to reject compiling it unless it's explicitly upcasted as an interface, which is the case of the functor for ``NonEmptyList``.

Try the latest code and let me know if it works in your scenario. I will see if I can upload a new nuget tonight.

**Comment by robkuz** [comment]
Yes I am still using the old nuget

**Comment by gmpl** [comment]
[Here's the new nuget](https://www.nuget.org/packages/FSharpPlus/1.0.0-CI00078) packege.
Let us know if it solves your issue.

**Comment by gmpl** [comment]
Hi @robkuz I was wondering if you updated to the new nuget.
If you did it and it solved this issue, please close it.
Thanks !

**Comment by robkuz** [comment]
Seems to work!
